title: Jeff Chan | Software Engineer
name: Jeff Chan | Software Engineer
description: Personal portfolio and landing page
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: minima
favicon_path: favicon.ico
repository: superjeffc/superjeffc.github.io
include:
  - _headers